name: Deploy Codebook

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6


    # AWS Auth
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_PASSWORD }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # Build & Push Backend
    - name: Build and push backend image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ secrets.ECR_REPOSITORY_NAME }}:latest \
          ./backend

        docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

        docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

    # Create new task definition version; Here I created id tag to use the task defination to run service
    - name: Create ECS new task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: file://infrastructre/task-defination.json
        container-name: codebook-backend
        image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

    # Deploy ECS with updated task defination
    - name: Deploy ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ secrets.ECS_CLUSTER_NAME }}
        service: ${{ secrets.ECS_SERVICE_NAME }}
        task-definition: ${{ steps.task-def.outputs.task-definition }}

    # Frontend build
    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    # Upload to S3
    - name: Upload frontend to S3
      run: |
        aws s3 sync frontend/build s3://${{ secrets.S3_BUCKET }} --delete

    # CloudFront invalidation
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
          --paths "/*"
