name: Deploy Codebook

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6


    # AWS Auth
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_PASSWORD }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      
    # Build & Push Backend
    - name: Build and push backend image
      id: build-image
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
      run: |
        # Remove any newlines from secrets
        AWS_ACCOUNT_ID="$(echo -n "$AWS_ACCOUNT_ID")"
        AWS_REGION="$(echo -n "$AWS_REGION")"
        ECR_REPOSITORY_NAME="$(echo -n "$ECR_REPOSITORY_NAME")"

        IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"

        echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_OUTPUT

        docker buildx build \
        --platform linux/amd64 \
        --push \
        -t "${IMAGE_URI}" \
        backend

    # Create new task definition version; Here I created id tag to use the new task definition to run service
    - name: Create ECS new task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: infrastructure/task-definition.json
        container-name: codebook-backend
        image: ${{ steps.build-image.outputs.IMAGE_URI }}

    # Deploy ECS with updated task defination
    - name: Deploy ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ secrets.ECS_CLUSTER_NAME }}
        service: ${{ secrets.ECS_SERVICE_NAME }}
        task-definition: ${{ steps.task-def.outputs.task-definition }}

    # Frontend build
    - name: Build frontend
      env: 
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        cd frontend
        npm install
        npm run build

    # Upload to S3
    - name: Upload frontend to S3
      run: |
        aws s3 sync frontend/build s3://${{ secrets.S3_BUCKET }} --delete

    # CloudFront invalidation
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
          --paths "/*"
